###
POST http://localhost:4000/products-api/product
Content-Type: application/json

{
    "productName":"tv",
    "price":7000,
    "brand":"sony"
}

###
POST http://localhost:4000/products-api/product
Content-Type: application/json

{
    "productName":"mobile",
    "price":8000,
    "brand":"samsung"
}
###
POST http://localhost:4000/users-api/users
Content-Type: application/json

{
    "name":"akhilesh",
    "email":"ak@gmail.com",
    "password":"dmart_shiva",
    "cart":[]
}

###
PUT http://localhost:4000/users-api/user-cart/user-id/698073e744797c5202d4c7a8/product-id/698189fb86cfd6a17d87d0c4

###
GET http://localhost:4000/users-api/users/698073e744797c5202d4c7a8